---
- name: Ensure the Ansible downloads directory exists
  file: >
    path={{ downloads_directory }}
    state=directory
- name: Ensure the user SSH directory exists
  file: >
    dest=/Users/{{ ansible_user_id }}/.ssh
    state=directory
- name: Generate ssh keypair
  openssh_keypair: >
    path=/Users/{{ ansible_user_id }}/.ssh/id_rsa
    size=4096
